services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: StoryNest-client
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      # - /app/node_modules
